- menu_name: "Servi√ßos"

- name: "Contato"
  url: "/contato/"
  title: "Contato"

#- name: "RSS"
#  url: "/feed.xml"
#  title: "Subscribe to RSS Feed"

#- name: "Atom"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
